import type { Metadata } from "next";
import localFont from "next/font/local";
import Headerpage from "@/components/Header";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import FotterPage from "@/components/fotter";
import { WishlistProvider } from "./WishlistContext/page";
import { ToastContainer } from "react-toastify";



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   <CartProvider>
          <WishlistProvider>

            <Headerpage />
            <ToastContainer/>
            {children}
            <FotterPage />
            
          </WishlistProvider>
        </CartProvider>
      </body>
    </html>
  );
}
